apiVersion: v1
kind: Service
metadata:
  labels:
    app: nopcommerce
  name: nopcommerce-svc
  namespace: release
spec:
  selector:
    app: nopcommerce
  ports:
    - nodePort: 30007
      targetPort: 5000
      port: 81
