apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
      name: customer-service-pod
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
      containers:
        - name: customer-service-app
          image: springcommunity/spring-petclinic-customers-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: petclinic-config
            - secretRef:
                name: petclinic-secret
          volumeMounts:
            - name: log-volume
              mountPath: /logs
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
        - name: log-sidecar
          image: busybox
          command: ["sh", "-c", "tail -f /logs/app.log"]
          volumeMounts:
            - name: log-volume
              mountPath: /logs
