apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: production
  name: petclinic-statefulset
spec:
  serviceName: "petclinic-db-svc"
  minReadySeconds: 20
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  replicas: 3
  selector:
    matchLabels:
      app: petclinic-statefulset
  template:
    metadata:
      name: petclinic-db-pod
      namespace: production
      labels:
        app: petclinic-statefulset
    spec:
      containers:
        - name: "petclinic-mysql-db"
          image: "mysql:8.0"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 3306
