apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vets
  template:
    metadata:
      labels:
        app: vets
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}

      containers:
        - name: app
          image: springcommunity/spring-petclinic-vets-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: petclinic-config
          volumeMounts:
            - name: log-volume
              mountPath: /logs

        - name: log-sidecar
          image: busybox
          command: ["sh", "-c", "tail -f /logs/app.log"]
          volumeMounts:
            - name: log-volume
              mountPath: /logs
